apiVersion: v1
kind: ConfigMap
metadata:
  name: store-configmap
data:
  DATABASE_HOST: postgres
  DATABASE_PORT: "5432"
  DATABASE_DB: store
  JWT_HTTP_ONLY: "true"
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_CREDENTIALS: "true"
  PRODUCT_API_URL: http://product:8080
  EXCHANGE_API_URL: http://exchange:8080
